# Generated by Django 6.0.7 on 2026-07-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField(verbose_name='利用日')),
                ('store_name', models.CharField(max_length=255, verbose_name='利用店名')),
                ('amount', models.IntegerField(verbose_name='利用金額')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='カテゴリー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
