# Generated by Django 6.0.7 on 2026-08-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽', '娯楽'), ('保険', '保険'), ('NISA', 'NISA'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
    ]
