# Generated by Django 6.0.7 on 2026-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='店名キーワード')),
                ('category', models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽', '娯楽'), ('保険', '保険'), ('NISA', 'NISA'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー')),
            ],
        ),
    ]
