# Generated by Django 6.0.7 on 2026-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_categoryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billing_month',
            field=models.CharField(default='2026-07', max_length=7, verbose_name='対象月'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽', '娯楽'), ('保険', '保険'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('サブスク', 'サブスク'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽', '娯楽'), ('保険', '保険'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('サブスク', 'サブスク'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
    ]
