# Generated by Django 6.1 on 2026-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_billing_month_alter_categoryrule_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rakuten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField(verbose_name='取引日')),
                ('amount', models.IntegerField(verbose_name='入出金')),
                ('zankin', models.IntegerField(verbose_name='取引後残高')),
                ('torihiki_name', models.CharField(max_length=255, verbose_name='内容')),
                ('category', models.CharField(choices=[('給料', '給料'), ('住民税', '住民税'), ('国民保健', '国民保健'), ('宝塚', '宝塚'), ('保険', '保険'), ('NISA', 'NISA'), ('家賃', '家賃'), ('現金引き出し', '現金引き出し'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
