# Generated by Django 6.1 on 2026-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_rakuten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakuten',
            name='category',
            field=models.CharField(choices=[('給料', '給料'), ('UFJからの送金額', 'UFJからの送金額'), ('住民税', '住民税'), ('国民保健', '国民保健'), ('宝塚', '宝塚'), ('保険', '保険'), ('NISA', 'NISA'), ('家賃', '家賃'), ('現金引き出し', '現金引き出し'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
    ]
