# Generated by Django 6.1 on 2026-08-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_rakuten_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakuten',
            name='billing_month',
            field=models.CharField(blank=True, max_length=7, verbose_name='対象月'),
        ),
    ]
