# Generated by Django 6.1 on 2026-08-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_rakuten_billing_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rakuten',
            old_name='torihiki_name',
            new_name='store_name',
        ),
    ]
