# Generated by Django 6.1 on 2026-08-21 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_rename_torihiki_name_rakuten_store_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='家計名')),
                ('members', models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='expense.household'),
        ),
        migrations.AddField(
            model_name='expense',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.household'),
        ),
        migrations.AddField(
            model_name='rakuten',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rakutens', to='expense.household'),
        ),
    ]
