# Generated by Django 6.1 on 2026-08-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_household_categoryrule_household_expense_household_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('rakuten', '楽天銀行'), ('ufj', '三菱UFJ')], max_length=15, verbose_name='銀行')),
                ('used_date', models.DateField(verbose_name='取引日')),
                ('amount', models.IntegerField(verbose_name='入出金')),
                ('zankin', models.IntegerField(verbose_name='取引後残高')),
                ('store_name', models.CharField(max_length=255, verbose_name='内容')),
                ('billing_month', models.CharField(blank=True, max_length=7, verbose_name='対象月')),
                ('category', models.CharField(choices=[('給料', '給料'), ('UFJからの送金額', 'UFJからの送金額'), ('住民税', '住民税'), ('国民保健', '国民保健'), ('宝塚', '宝塚'), ('保険', '保険'), ('NISA', 'NISA'), ('家賃', '家賃'), ('現金引き出し', '現金引き出し'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rakutens', to='expense.household')),
            ],
        ),
        migrations.DeleteModel(
            name='Rakuten',
        ),
    ]
