# Generated by Django 6.0.7 on 2026-08-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_bank_delete_rakuten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='expense.household'),
        ),
    ]
