# Generated by Django 6.0.7 on 2026-08-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_bank_owner_expense_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('給料', '給料'), ('入金', '入金'), ('住民税', '住民税'), ('国民保健', '国民保健'), ('宝塚', '宝塚'), ('保険', '保険'), ('NISA', 'NISA'), ('家賃', '家賃'), ('現金引き出し', '現金引き出し'), ('カード引き落とし', 'カード引き落とし'), ('サービス', 'サービス'), ('入金', '入金'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽・趣味', '娯楽・趣味'), ('家保険', '家保険'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('旅行', '旅行'), ('定期代', '定期代'), ('交通費', '交通費'), ('サブスク', 'サブスク'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽・趣味', '娯楽・趣味'), ('家保険', '家保険'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('旅行', '旅行'), ('定期代', '定期代'), ('交通費', '交通費'), ('サブスク', 'サブスク'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
    ]
