# Generated by Django 6.0.7 on 2026-08-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_alter_bank_category_alter_categoryrule_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(choices=[('rakuten', '楽天銀行'), ('ufj', '三菱UFJ'), ('roukin', 'ろうきん')], max_length=15, verbose_name='銀行'),
        ),
        migrations.CreateModel(
            name='BankCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='店名キーワード')),
                ('category', models.CharField(choices=[('給料', '給料'), ('入金', '入金'), ('住民税', '住民税'), ('国民保健', '国民保健'), ('宝塚', '宝塚'), ('保険', '保険'), ('NISA', 'NISA'), ('家賃', '家賃'), ('現金引き出し', '現金引き出し'), ('カード引き落とし', 'カード引き落とし'), ('サービス', 'サービス'), ('入金', '入金'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_category_rules', to='expense.household')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='店名キーワード')),
                ('category', models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽・趣味', '娯楽・趣味'), ('家保険', '家保険'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('旅行', '旅行'), ('定期代', '定期代'), ('交通費', '交通費'), ('サブスク', 'サブスク'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category_rules', to='expense.household')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryRule',
        ),
    ]
