# Generated by Django 6.0.7 on 2026-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_alter_bank_bank_bankcategoryrule_expensecategoryrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('給料', '給料'), ('入金', '入金'), ('現金引き出し', '現金引き出し'), ('国保・住民税・年金類', '国保・住民税・年金類'), ('娯楽・趣味', '娯楽・趣味'), ('NISA', 'NISA'), ('家賃', '家賃'), ('カード引き落とし', 'カード引き落とし'), ('サービス(還元など)', 'サービス(還元など)'), ('家具家電・設備', '家具家電・設備'), ('保険（家や生命など）', '保険（家や生命など）'), ('日用品', '日用品'), ('その他', 'その他'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='bankcategoryrule',
            name='category',
            field=models.CharField(choices=[('給料', '給料'), ('入金', '入金'), ('現金引き出し', '現金引き出し'), ('国保・住民税・年金類', '国保・住民税・年金類'), ('娯楽・趣味', '娯楽・趣味'), ('NISA', 'NISA'), ('家賃', '家賃'), ('カード引き落とし', 'カード引き落とし'), ('サービス(還元など)', 'サービス(還元など)'), ('家具家電・設備', '家具家電・設備'), ('保険（家や生命など）', '保険（家や生命など）'), ('日用品', '日用品'), ('その他', 'その他'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('食費(自炊)', '食費(自炊)'), ('食費(外食)', '食費(外食)'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽・趣味', '娯楽・趣味'), ('保険（家や生命など）', '保険（家や生命など）'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('旅行・レジャー', '旅行・レジャー'), ('定期代', '定期代'), ('交通費', '交通費'), ('サブスク', 'サブスク'), ('光熱費', '光熱費'), ('サロン代', 'サロン代'), ('車関係（ガソリン・車保険など）', '車関係（ガソリン・車保険など）'), ('ETC', 'ETC'), ('携帯料金', '携帯料金'), ('家具家電・設備', '家具家電・設備'), ('医療費', '医療費'), ('その他', 'その他'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='expensecategoryrule',
            name='category',
            field=models.CharField(choices=[('食費(自炊)', '食費(自炊)'), ('食費(外食)', '食費(外食)'), ('日用品', '日用品'), ('衣類', '衣類'), ('娯楽・趣味', '娯楽・趣味'), ('保険（家や生命など）', '保険（家や生命など）'), ('NISA', 'NISA'), ('プレゼント', 'プレゼント'), ('旅行・レジャー', '旅行・レジャー'), ('定期代', '定期代'), ('交通費', '交通費'), ('サブスク', 'サブスク'), ('光熱費', '光熱費'), ('サロン代', 'サロン代'), ('車関係（ガソリン・車保険など）', '車関係（ガソリン・車保険など）'), ('ETC', 'ETC'), ('携帯料金', '携帯料金'), ('家具家電・設備', '家具家電・設備'), ('医療費', '医療費'), ('その他', 'その他'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー'),
        ),
    ]
