# Generated by Django 6.0.7 on 2026-08-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_alter_bank_category_alter_bankcategoryrule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='ai_used',
            field=models.BooleanField(default=False, verbose_name='AI分類'),
        ),
        migrations.AddField(
            model_name='bank',
            name='ml_used',
            field=models.BooleanField(default=False, verbose_name='機械学習分類'),
        ),
        migrations.AddField(
            model_name='expense',
            name='ai_used',
            field=models.BooleanField(default=False, verbose_name='AI分類'),
        ),
        migrations.AddField(
            model_name='expense',
            name='ml_used',
            field=models.BooleanField(default=False, verbose_name='機械学習分類'),
        ),
    ]
