# Generated by Django 6.0.7 on 2026-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0018_bank_ai_used_bank_ml_used_expense_ai_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='ai_used',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='ml_used',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='ai_used',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='ml_used',
        ),
        migrations.AddField(
            model_name='bank',
            name='classification_method',
            field=models.CharField(blank=True, choices=[('ai', 'AI分類'), ('memory', '記憶分類'), ('ml', '機械学習')], max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='classification_method',
            field=models.CharField(blank=True, choices=[('ai', 'AI分類'), ('memory', '記憶分類'), ('ml', '機械学習')], max_length=10),
        ),
    ]
