# Generated by Django 6.0.7 on 2026-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0019_remove_bank_ai_used_remove_bank_ml_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='classification_method',
            field=models.CharField(blank=True, choices=[('ai', 'AI分類'), ('memory', '記憶分類'), ('ml', '機械学習'), ('rule', 'ルール付け分類')], max_length=10, verbose_name='分類方法'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='classification_method',
            field=models.CharField(blank=True, choices=[('ai', 'AI分類'), ('memory', '記憶分類'), ('ml', '機械学習'), ('rule', 'ルール付け分類')], max_length=10),
        ),
    ]
