# Generated by Django 6.1 on 2026-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0021_nisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('給料', '給料'), ('入金', '入金'), ('送金', '送金'), ('現金引き出し', '現金引き出し'), ('国保・住民税・年金類', '国保・住民税・年金類'), ('娯楽・趣味', '娯楽・趣味'), ('NISA', 'NISA'), ('家賃', '家賃'), ('カード引き落とし', 'カード引き落とし'), ('サービス(還元など)', 'サービス(還元など)'), ('家具家電・設備', '家具家電・設備'), ('保険（家や生命など）', '保険（家や生命など）'), ('日用品', '日用品'), ('食費', '食費'), ('衣類', '衣類'), ('その他', 'その他'), ('未分類', '未分類')], default='未分類', max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='bankcategoryrule',
            name='category',
            field=models.CharField(choices=[('給料', '給料'), ('入金', '入金'), ('送金', '送金'), ('現金引き出し', '現金引き出し'), ('国保・住民税・年金類', '国保・住民税・年金類'), ('娯楽・趣味', '娯楽・趣味'), ('NISA', 'NISA'), ('家賃', '家賃'), ('カード引き落とし', 'カード引き落とし'), ('サービス(還元など)', 'サービス(還元など)'), ('家具家電・設備', '家具家電・設備'), ('保険（家や生命など）', '保険（家や生命など）'), ('日用品', '日用品'), ('食費', '食費'), ('衣類', '衣類'), ('その他', 'その他'), ('未分類', '未分類')], max_length=50, verbose_name='カテゴリー'),
        ),
    ]
