# Generated by Django 6.1 on 2026-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0023_alter_bank_category_alter_bankcategoryrule_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nisa',
            name='recorded_date',
            field=models.DateField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
